.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 10/22/11               \" DATE 
.Dt image-slicer 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm image-slicer
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd Slices an image in tiles.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Fl TileSize Ar float
.Fl ImagePath Ar string
.Op Fl OutputPath Ar string
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm 
slices the input image into tiles of at least tile size pixels.
.Pp                      \" Inserts a space
.Bl -tag -width -indent  \" Differs from above in tag removed 
.It Fl TileSize Ar float
The size of the tiles side, in pixels.
.It Fl ImagePath Ar string
The path of the image we want to tile.
.It Op Fl OutputPath Ar string
The output path where the tiles will be written. If not specified, the tiles will be written in the same directory as the input image.
.El                      \" Ends the list
.Pp
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner